<?php

return [
    'pcl5_demo_items' => [
        ['id' => 'pcl_1', 'text' => 'Repeated, disturbing memories, thoughts, or images of the stressful experience?'],
        ['id' => 'pcl_2', 'text' => 'Repeated, disturbing dreams of the stressful experience?'],
        ['id' => 'pcl_3', 'text' => 'Suddenly acting or feeling as if the stressful experience were happening again?'],
        ['id' => 'pcl_4', 'text' => 'Feeling very upset when something reminded you of the stressful experience?'],
        ['id' => 'pcl_5', 'text' => 'Having strong physical reactions when something reminded you of the experience?'],
        ['id' => 'pcl_6', 'text' => 'Avoiding memories, thoughts, or feelings related to the stressful experience?'],
        ['id' => 'pcl_7', 'text' => 'Avoiding external reminders (people, places, conversations) of the stressful experience?'],
        ['id' => 'pcl_8', 'text' => 'Trouble remembering important parts of the stressful experience?'],
    ],

    'pcl5_response_labels' => [
        0 => 'Not at all',
        1 => 'A little bit',
        2 => 'Moderately',
        3 => 'Quite a bit',
        4 => 'Extremely',
    ],

    /*
     * Demo uses 8 PCL-5 items (max score 32). Threshold scaled from full PCL-5 cutoff of 33/80.
     */
    'pcl5_demo_threshold' => 13,

    'admin_notification_emails' => [
        'rucampbell@connectionscounseling.org',
        'rmohrmann@gmail.com',
    ],

    'baseline_surveys' => [
        'pcl-5' => [
            'route_name' => 'participant.assessments.pcl5',
            'store_route_name' => 'participant.assessments.pcl5.store',
            'title' => 'PCL-5 Baseline Assessment',
            'label' => 'PCL-5',
            'description' => 'Complete the abbreviated PCL-5 to establish your baseline PTSD symptom score.',
            'instructions' => 'Over the last month, how much were you bothered by each item below?',
            'items_key' => 'pcl5_demo_items',
            'labels_key' => 'pcl5_response_labels',
            'min' => 0,
            'max' => 4,
            'default' => 3,
            'score_max' => 32,
        ],
        'ace' => [
            'route_name' => 'participant.assessments.ace',
            'store_route_name' => 'participant.assessments.ace.store',
            'title' => 'Adverse Childhood Experiences',
            'label' => 'ACE',
            'description' => 'Complete the Adverse Childhood Experiences assessment.',
            'intro' => [
                'Our relationships and experiences, even those in childhood, can affect our health and well-being. Difficult childhood experiences are very common. Please tell us whether you have had any of the experiences listed below, as they may be affecting your health today or may affect your health in the future.',
                'This information will help you and your provider better understand how to work together to support your health and well-being. Collating of information for research or assessment purposes will be done without sharing any identifying information.',
                'Your confidentiality is protected. Your identifying information will not be shared with anyone other than the therapist with whom you are working.',
            ],
            'fields' => [
                [
                    'id' => 'participant_initials',
                    'label' => 'What are the initials of your first and last name?',
                    'type' => 'text',
                    'max' => 10,
                    'autocomplete' => 'off',
                ],
                [
                    'id' => 'participant_email',
                    'label' => 'What is your email address?',
                    'type' => 'email',
                    'autocomplete' => 'email',
                ],
            ],
            'instructions' => 'Below is a list of 10 categories of Adverse Childhood Experiences (ACEs). From the list below, please place a checkmark next to each ACE category that you experienced prior to your 18th birthday. Yes = 1, No = 0.',
            'closing' => 'Thank you for answering these questions about your childhood experiences. Your therapist will be able to talk with you about the results.',
            'items_key' => 'ace_items',
            'labels_key' => 'ace_response_labels',
            'min' => 0,
            'max' => 1,
            'default' => null,
            'score_max' => 10,
        ],
        'des-ii' => [
            'route_name' => 'participant.assessments.des-ii',
            'store_route_name' => 'participant.assessments.des-ii.store',
            'title' => 'DES-II Baseline Survey',
            'label' => 'DES-II',
            'description' => 'Complete the Dissociative Experiences Scale-II.',
            'instructions' => 'For each item, choose the percentage of time this experience happens to you.',
            'items_key' => 'des_ii_items',
            'labels_key' => 'des_ii_response_labels',
            'min' => 0,
            'max' => 100,
            'step' => 10,
            'default' => null,
            'score_max' => 100,
        ],
    ],

    'ace_items' => [
        ['id' => 'ace_1', 'text' => 'Did you feel that you did not have enough to eat, had to wear dirty clothes, or had no one to protect or take care of you?'],
        ['id' => 'ace_2', 'text' => 'Did you lose a parent through divorce, abandonment, death, or other reason?'],
        ['id' => 'ace_3', 'text' => 'Did you live with anyone who was depressed, mentally ill, or attempted suicide?'],
        ['id' => 'ace_4', 'text' => 'Did you live with anyone who had a problem with drinking or using drugs, including prescription drugs?'],
        ['id' => 'ace_5', 'text' => 'Did your parents or adults in your home ever hit, punch, beat, or threaten to harm each other?'],
        ['id' => 'ace_6', 'text' => 'Did you live with anyone who went to jail or prison?'],
        ['id' => 'ace_7', 'text' => 'Did a parent or adult in your home ever swear at you, insult you, or put you down?'],
        ['id' => 'ace_8', 'text' => 'Did a parent or adult in your home ever hit, beat, kick, or physically hurt you in any way?'],
        ['id' => 'ace_9', 'text' => 'Did you feel that no one in your family loved you or thought you were special?'],
        ['id' => 'ace_10', 'text' => 'Did you experience unwanted sexual contact (such as fondling or oral/anal/vaginal intercourse/penetration)?'],
    ],

    'ace_response_labels' => [
        0 => 'No',
        1 => 'Yes',
    ],

    'des_ii_items' => [
        ['id' => 'des_1', 'text' => 'Some people have the experience of driving or riding in a car and suddenly realizing that they do not remember what happened during all or part of the trip.'],
        ['id' => 'des_2', 'text' => 'Some people find that sometimes they are listening to someone talk and suddenly realize that they did not hear part or all of what was said.'],
        ['id' => 'des_3', 'text' => 'Some people have the experience of finding themselves in a place and having no idea how they got there.'],
        ['id' => 'des_4', 'text' => 'Some people have the experience of finding themselves dressed in clothes that they do not remember putting on.'],
        ['id' => 'des_5', 'text' => 'Some people have the experience of finding new things among their belongings that they do not remember buying.'],
        ['id' => 'des_6', 'text' => 'Some people sometimes find that they are approached by people they do not know who call them by another name or insist that they have met them before.'],
        ['id' => 'des_7', 'text' => 'Some people sometimes have the experience of feeling as though they are standing next to themselves or watching themselves do something, as if they were looking at another person.'],
        ['id' => 'des_8', 'text' => 'Some people are told that they sometimes do not recognize friends or family members.'],
        ['id' => 'des_9', 'text' => 'Some people find that they have no memory for some important events in their lives, such as a wedding or graduation.'],
        ['id' => 'des_10', 'text' => 'Some people have the experience of being accused of lying when they do not think that they have lied.'],
        ['id' => 'des_11', 'text' => 'Some people have the experience of looking in a mirror and not recognizing themselves.'],
        ['id' => 'des_12', 'text' => 'Some people have the experience of feeling that other people, objects, and the world around them are not real.'],
        ['id' => 'des_13', 'text' => 'Some people have the experience of feeling that their body does not seem to belong to them.'],
        ['id' => 'des_14', 'text' => 'Some people have the experience of sometimes remembering a past event so vividly that they feel as if they were reliving that event.'],
        ['id' => 'des_15', 'text' => 'Some people have the experience of not being sure whether things that they remember happening really did happen or whether they just dreamed them.'],
        ['id' => 'des_16', 'text' => 'Some people have the experience of being in a familiar place but finding it strange and unfamiliar.'],
        ['id' => 'des_17', 'text' => 'Some people find that when they are watching television or a movie, they become so absorbed in the story that they are unaware of other events happening around them.'],
        ['id' => 'des_18', 'text' => 'Some people find that they become so involved in a fantasy or daydream that it feels as though it is really happening to them.'],
        ['id' => 'des_19', 'text' => 'Some people find that they are sometimes able to ignore pain.'],
        ['id' => 'des_20', 'text' => 'Some people find that they sometimes sit staring off into space, thinking of nothing, and are not aware of the passage of time.'],
        ['id' => 'des_21', 'text' => 'Some people sometimes find that when they are alone they talk out loud to themselves.'],
        ['id' => 'des_22', 'text' => 'Some people find that in one situation they may act so differently compared with another situation that they feel almost as if they were two different people.'],
        ['id' => 'des_23', 'text' => 'Some people sometimes find that in certain situations they are able to do things with amazing ease and spontaneity that would usually be difficult for them.'],
        ['id' => 'des_24', 'text' => 'Some people sometimes find that they cannot remember whether they have done something or have just thought about doing it.'],
        ['id' => 'des_25', 'text' => 'Some people find evidence that they have done things that they do not remember doing.'],
        ['id' => 'des_26', 'text' => 'Some people sometimes find writings, drawings, or notes among their belongings that they must have done but cannot remember doing.'],
        ['id' => 'des_27', 'text' => 'Some people sometimes find that they hear voices inside their head that tell them to do things or comment on things that they are doing.'],
        ['id' => 'des_28', 'text' => 'Some people sometimes feel as if they are looking at the world through a fog or veil, so that people and objects appear far away or unclear.'],
    ],

    'des_ii_response_labels' => [
        0 => '0%',
        10 => '10%',
        20 => '20%',
        30 => '30%',
        40 => '40%',
        50 => '50%',
        60 => '60%',
        70 => '70%',
        80 => '80%',
        90 => '90%',
        100 => '100%',
    ],
];
